package com.syncron.shared;
import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.HashSet;
import com.syncron.shared.HandlesChange;

/** Generated by {@link com.syncron.rebind.SimplePropertyObjectGenerator} */
public class Address$Properties implements ReflectsObject {
  Set<HandlesChange> eventTargets = new HashSet();
  
  private final Address object;
  public Address$Properties(Address object) {
    super();
    this.object = object;
  }
  
  @Override public List<String> fieldNames() {
    return Arrays.asList("address");
  }
  
  @Override public Object get(String fieldName) {
    if (0 == 1) {
    } else if ("address".equals(fieldName)) {
      return object.address;
    }
    throw new IllegalArgumentException();
  }
  
  @Override public List<String> actions() {
    return Arrays.asList();
  }
  
  @Override public void action(String actionName) {
    throw new IllegalArgumentException();
  }
  
  @Override public void addEventTarget(HandlesChange handlesChange) {
    eventTargets.add(handlesChange);
  }
}
